### PR TITLE
fix: add null as allowed type for quote

### PR DESCRIPTION
**Pull request by vityas-off**

### CODE REVIEW

**Comment by wdavidw** [comment]
Isnt marking the field as optional enough ? Also, please update the test in "./test/api.types.ts" to illustrate your addition.

**Comment by vityas-off** [comment]
From documentation: "Optional character surrounding a field; one character only; disabled if null, false or empty; defaults to double quote." So if I use null as a value here ts will not compile, but using null here is ok.

**Comment by wdavidw** [comment]
I have imported from your test the `options.quote = null` part. If I understood you well, I shall have get an error but I didn't.

**Comment by vityas-off** [comment]
Here is example of code
```ts
import parseCsv from "csv-parse";

const parser = parseCsv({
  quote: null
});
```
when trying to compile I'm getting this error `Argument of type '{ quote: null; }' is not assignable to parameter of type 'Callback'.
  Object literal may only specify known properties, and 'quote' does not exist in type 'Callback'.` Which is correct since null not listed as possible type in type declarations.

**Comment by wdavidw** [comment]
In such case, the below tests shall fail, right ?

```ts
    it('quote 1', () => {
      const options: Options = {}
      options.quote = null
    })
```

```ts
    it('quote 2', () => {
      const parser = parse({
        quote: null
      });
    })
```

But they don't. I'll be happy to apply your changes once I can reproduce the error. @yonilerner would you have any input on this one ?

**Comment by vityas-off** [comment]
This test and one other will fail if run like `TS_NODE_COMPILER_OPTIONS='{"strictNullChecks":true}' npx mocha test/**/*.{coffee,ts}`. Hope this will help.

**Comment by wdavidw** [comment]
Wonderful, it failed! Merging now...

**Pull request merged**
