### PR TITLE
field.toString().trim()

### PR DESCRIPTION
**Pull request by odykyi**
fix error 

caused by: TypeError: field.trim is not a function

error happens when field is number

### CODE REVIEW

**Comment by odykyi** [comment]
@rmm5t @pyrotechnick @markstos @wdavidw 

review pls

**Comment by wdavidw** [comment]
I will merge it and later improve it because,  this will fail if cast return something without the `toString` function such as `undefined`, `null`, boolean..

**Comment by wdavidw** [comment]
Question now, should we skip `null` and `undefined` value, probably, I'll update the doc in that regard

**Comment by wdavidw** [comment]
Version 4.6.0 fixed the issue

**Pull request merged**
