### PR TITLE
Handle duplicate column names if columns: true

### PR DESCRIPTION
**Pull request by winton**
When duplicate columns are defined and `columns: true`, create an array of values in the final record.

### CODE REVIEW

**Comment by winton** [comment]
Might address #80

**Comment by wdavidw** [comment]
I am thinking about preserving the current as is and introducing a new option such as `columns_duplicates_to_array`

**Comment by vrmerlin** [comment]
Is there a timeframe for this one? I need support for multiple columns with the same header name (for JIRA issue exports, which has multiple Attachment entries in their CSV).

**Comment by wdavidw** [comment]
Let me work on it, I forgot about that one.

**Comment by vrmerlin** [comment]
Sweet! Thanks so much.

**Comment by wdavidw** [comment]
Version 4.10.0 introduces the new `columns_duplicates_to_array: new option` option

**Pull request merged**
