### PR TITLE
Fix parsing for BOM character

### PR DESCRIPTION
**Pull request by OlegRakovitch**
From nodejs documentation: 
```
0 is returned if target is the same as buf
```
Source: https://nodejs.org/api/buffer.html#buffer_buf_compare_target_targetstart_targetend_sourcestart_sourceend

### CODE REVIEW

**Comment by wdavidw** [comment]
Could you please add a unit test which is fixed by your proposal?

**Comment by OlegRakovitch** [comment]
@wdavidw Sure. I added this unit test, it should be red on master.

**Comment by wdavidw** [comment]
Thank you very much @OlegRakovitch

**Comment by wdavidw** [comment]
Version 4.4.2 is published with your fix.

**Pull request merged**
