### PR TITLE
Allow injection of custom pasring function

### PR DESCRIPTION
**Pull request by willfarrell**
Specific use cases I'm thinking for this would be:
- removing the thousand separator in numbers
- convert lat,lng to array or object
- among many many more

ex:
```js
options = {
  ...,
  auto_parse: function(value) { return value+' 00:05:00'; } 
}
```

Related to #160

### CODE REVIEW

**Comment by wdavidw** [comment]
Not sure why you would like to add a new option, if you wish to provide the same fonctionnality than in #160, then why not apply to same strategy to the existing "auto_parse" option ?

**Comment by willfarrell** [comment]
Oh, good idea. Override the whole parse function altogether.

**Comment by wdavidw** [comment]
Could you see if you could rebase or do something, for same reason github doesnt let me "rebase and merge" automatically

**Comment by willfarrell** [comment]
Git hub really needs a button for that. It was easier to just create a new PR. #162

**Pull request closed without merging**
