### PR TITLE
feature: add aditional information in 'skip' event

### PR DESCRIPTION
**Pull request by Ginden**

### CODE REVIEW

**Comment by wdavidw** [comment]
Instead of passing `headers` as an array, could you provide a `context` object with a header key inside, this will provide more flexibility in the long term.

**Comment by jbgrunewald** [comment]
This would be very helpful if included. What's the chances of this getting merged soon?

**Comment by wdavidw** [comment]
Ok, I'll make the changes myself

**Comment by jbgrunewald** [comment]
woot

**Comment by wdavidw** [comment]
I have published version 4.5 with the initial code to start normalizing and enriching errors. This is backward compatible but not fully implemented. The idea is that all errors will extend the new `CsvError` object which introduces a unique code for each error documented on the [error documentation page](https://csv.js.org/parse/errors/). The error object may contain contextual properties, also documented and some general state-related information which are not yet implemented.

**Pull request merged**
